# Generated by Django 6.0.3 on 2026-04-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_moodentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodentry',
            name='diary_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
