# Generated by Django 6.0.3 on 2026-04-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_moodentry_diary_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodentry',
            name='intensity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
